### ISSUE TITLE
Wyświetlanie lekcji

### ISSUE THREAD

**Issue by orzecho** [orzecho/pja-cms-2018#14]
* wyświetlanie plików lekcji
* wyświetlanie słówek (analogicznie jak przy edycji tylko bez możliwości edycji)
* wyświetlanie tagów

**Comment by hamboomger** [comment]
My już to mamy? Jest jakiś commit związany z tym issue?

**Comment by orzecho** [comment]
Tak, to już zostało zmergowane z tego co kojarzę @hamboomger
